### ISSUE TITLE
Use element acquired by driver.execute

### ISSUE THREAD

**Issue by zoechi** [google/webdriver.dart#100]
I look up elements using 
```dart
var elements = await driver.execute('return document.querySelector('someSelector')
    .shadowRoot.querySelectorAll("otherSelector");', []).toList();
var cell = elements[3];
var text = await cell.text;
await cell.click();
```
The last line results in 

>  StaleElementReferenceException (10): stale element reference: element is not attached to the page document
    (Session info: chrome=44.0.2403.157)
    (Driver info: chromedriver=2.19.346067 (6abd8652f8bc7a1d825962003ac88ec6a37a82f1),platform=Linux 4.1.0-1-amd64 x86_64) (WARNING: The server did not provide any stacktrace information)
  Command duration or timeout: 16 milliseconds
  For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
  Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
  System info: host: '7705b8531113', ip: '172.17.1.91', os.name: 'Linux', os.arch: 'amd64', os.version: '4.1.0-1-amd64', java.version: '1.8.0_45-internal'
  Driver info: org.openqa.selenium.chrome.ChromeDriver
  Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=/tmp/.com.google.Chrome.F3Ryk6}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=44.0.2403.157, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
  Session ID: f10548f173186772ad19f62227f175c5
  package:webdriver                                         WebElement.click

The same test worked previously with `findElements(const By.cssSelector('selector /deep/ otherSelector'));` but this isn't supported in browsers except Chrome.

Should this work?
Could this be an issue in this package or is this an issue of the ChromeDriver?

**Comment by DrMarcII** [comment]
It seems like an issue with chromedriver to me, but I am not sure.

**Comment by zoechi** [comment]
Ok, I'll investigate further and report back when I make progress.

**Comment by zoechi** [comment]
This http://japhr.blogspot.co.at/2014/12/on-polymer-protractor-and-page-objects.html?m=1 seems to be about the same issue. It looks like a shadow DOM + chromedriver issue.
