### ISSUE TITLE
PUT request

### ISSUE THREAD

**Issue by andrey-zakharov** [google/webdriver.dart#102]
Looks like there is no any possibility to perfrom PUT (and any others HEAD, OPTIONS) http requests.
Exposed generic method "request( String method, Uri uri, [Map params] )" solved the issue completely.

**Comment by DrMarcII** [comment]
I am not aware of any wire protocol commands that use PUT, HEAD or OPTIONS. What do you need this for?

**Comment by andrey-zakharov** [comment]
Already solve it by
```
  static final String _UPLOAD_JS = """
      var req = new XMLHttpRequest();
      var callback = arguments[arguments.length - 1];
      req.upload.addEventListener('load', function (evt) {
        // completer callback
        callback(req);
      });

      req.open( "PUT", "$baseUrl/storage/" + arguments[0] );
      req.send( arguments[1] );
  """;

var req = await driver.executeAsync( _UPLOAD_JS, [TEST_FILE, TEST_TEXT]);
```

if someone needs it.

**Comment by tylersnavely-wf** [comment]
WebDriver is a project for interacting with a browser the way a user would, and therefore does not have any APIs for making HTTP requests directly.
