### ISSUE TITLE
Add back captureScreenshotAsBase64

### ISSUE THREAD

**Issue by BlackHC** [google/webdriver.dart#112]
The sync webdriver provides both captureScreenshot and captureScreenshotAsBase64.

Atm:
```
  /// Take a screenshot of the current page as PNG.
  Stream<int> captureScreenshot() async* {
    var encoded = await getRequest('screenshot');
    yield* new Stream.fromIterable(CryptoUtils.base64StringToBytes(encoded));
  }
```
This could be split up again into two methods.

**Comment by DrMarcII** [comment]
What is the use case?

**Comment by BlackHC** [comment]
We use it to log a screenshot in our html log using an embedded "data:" URL. It doesn't really seem to make sense to decode from base64 to encode right again. What do you think?

**Comment by DrMarcII** [comment]
Feel free to send a PR.
