### ISSUE TITLE
Slow async captureScreenshot

### ISSUE THREAD

**Issue by BlackHC** [google/webdriver.dart#114]
async captureScreenshot is about ~40x slower than the synchronous version (taking a 800x600 screenshot takes ~20s vs 500ms). This is because captureScreenshot returns a Stream<int> containing the bytes making up the png screenshot and we have to call Stream.toList() to write the screenshot to a file. Compared to returning the list directly, it is 5000x slower in a test. (100x slower because of wrapping it in a Stream and async*/yield* and 50x slower because of unittest & stack_trace).

The suggested solution is to add a captureScreenshotAsList method back that returns a simple List<int>.
See also captureScreenshotAsBase64 #112

**Comment by goderbauer** [comment]
Thanks for the contribution.
