### ISSUE TITLE
Unable to perform "ctrl+click"

### ISSUE THREAD

**Issue by andrey-zakharov** [google/webdriver.dart#123]
couldn't find any "keyDown, keyUp" commands.

**Comment by goderbauer** [comment]
Did you try this?
https://github.com/google/webdriver.dart/blob/master/test/src/keyboard.dart#L69

**Comment by andrey-zakharov** [comment]
sendChord doesn't help, as we should hold ctrl and click by mouse, sendChord, as I can understand, sending only "ctrl+a" key codes and not holding key modificators.

**Comment by patkujawa-wf** [comment]
I would also really appreciate this functionality. Looks like we need to add support for [17.5 Perform Actions](https://w3c.github.io/webdriver/webdriver-spec.html#perform-actions), which is a bit more clearly described in https://github.com/SeleniumHQ/selenium/wiki/Advanced-User-Interactions. And here's a python [Action Chains](http://selenium-python.readthedocs.io/api.html#module-selenium.webdriver.common.action_chains) API, for comparison.

**Comment by DrMarcII** [comment]
If you do the following it should get the desired behavior:

```dart
// modifier keys are supposed to be sticky across multiple calls when using keyboard.sendKeys:
// https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidkeys
await driver.keyboard.sendKeys(Keyboard.control);
await driver.mouse.click(element);
// a second call to the same modifier key releases it:
// https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidelementidvalue
await driver.keyboard.sendKeys(Keyboard.control);
```

If this doesn't work, it indicates a bug in the remote end, not a bug in webdriver.dart.

As for the /actions endpoint, no remote ends implement yet (although marionette/geckodriver will hopefully do so soon). When it is available in some endpoint, we will see about implementing it here.

**Comment by patkujawa-wf** [comment]
Thanks for the code, that works (in Chrome) with a tweak (`driver.mouse.click()` doesn't take an element, it takes an optional mouse button). I tested with SauceLabs in Chrome on Windows and Mac and it worked great. Firefox and IE11 on Windows both **don't** support the `moveTo` command, so dice there, unfortunately.
