### ISSUE TITLE
A CHANGELOG.md would be nice

### ISSUE THREAD

**Issue by zoechi** [google/webdriver.dart#124]
with notes about what changed from one release to the next

**Comment by goderbauer** [comment]
Currently, we are documenting changes in the releases tab on github:
https://github.com/google/webdriver.dart/releases

Is this what you were looking for?

**Comment by zoechi** [comment]
Perhaps a `CHANGELOG.md` with only a link to this tab?
pub.dartlang.org shows this file if it exists for a published package.

**Comment by goderbauer** [comment]
Good idea, want to send me a PR for it? :)
