### ISSUE TITLE
Enable generics in waitFor

### ISSUE THREAD

**Issue by travissanderson-wf** [google/webdriver.dart#130]
For consuming libraries to obey strong mode, we will need to enable the commented-out generics in the waitFor definition [here](https://github.com/google/webdriver.dart/blob/master/lib/support/async.dart#L28).  This would require bumping the SDK restriction to 1.21+.  Is this a change you would be open to accepting?

**Comment by DrMarcII** [comment]
Yes.

**Comment by travissanderson-wf** [comment]
the code change is pretty trivial, just uncommenting the generic definitions already in there for the most part, but I have no idea how to get bazel running tests in a Dart 1.21 environment

**Comment by DrMarcII** [comment]
dart_rules are currently using 1.21.0-dev.3.0 (https://github.com/dart-lang/rules_dart/blob/master/dart/build_rules/repositories.bzl#L69). Is that not sufficient?

**Comment by travissanderson-wf** [comment]
That should be, when I run bazel test locally this is the type of error I am seeing though:

```
FAIL: //test:io_test_chromium-native (see /private/var/tmp/_bazel_travissanderson/48afd87cd8d3f5caedafcff5ca1c95db/execroot/webdriver.dart/bazel-out/local-fastbuild/testlogs/test/io_test_chromium-native/test.log).
'package:webdriver/support/async.dart': error: line 28 pos 18: generic functions not supported
Future<T> waitFor<T>(T condition(),

**Comment by travissanderson-wf** [comment]
I opened a PR to see if travis-ci does better than local-guy-named-travis https://github.com/google/webdriver.dart/pull/131

**Comment by travissanderson-wf** [comment]
This was addressed by 131, would you be able to publish a release including this change at your convenience? thanks!

**Comment by DrMarcII** [comment]
Release has been published.

**Comment by travissanderson-wf** [comment]
Thanks!
