### ISSUE TITLE
Does dart webdriver support timeline recording?

### ISSUE THREAD

**Issue by laike9m** [google/webdriver.dart#144]
Like in chrome devtools?
![image](https://cloud.githubusercontent.com/assets/2592205/22817722/ebece822-efa3-11e6-81e9-18773e66dd79.png)

Thank you.

**Comment by DrMarcII** [comment]
I think this data is available in the Chromedriver's performance logs (https://sites.google.com/a/chromium.org/chromedriver/logging/performance-log). You should be to get this by setting the appropriate capability and getting the logs:

```dart
var driver = await createDriver(desired: {
  "loggingPrefs": {LogType.performance: LogLevel.all}
});
// do whatever
...
for (LogEntry entry in await driver.logs.get(LogType.performance).toList()) {
   // do something with the log entries.

}
```
