### ISSUE TITLE
1.2.4 is not published, published version of 1.2.3 does not match tag

### ISSUE THREAD

**Issue by greglittlefield-wf** [google/webdriver.dart#175]
I'm looking to use the `FutureOr<T>` version of `waitFor`, which was added in version 1.2.3 of this package: https://github.com/google/webdriver.dart/blob/v1.2.3/lib/support/async.dart#L28

However, that change doesn't seem to be present in the Pub archive of 1.2.3: https://storage.googleapis.com/pub-packages/packages/webdriver-1.2.3.tar.gz

While looking into this, I also noticed that 1.2.4 was tagged but not published (see published versions here: https://pub.dartlang.org/packages/webdriver#pub-pkg-tab-versions).

**Comment by devoncarew** [comment]
Can we close this issue?

**Comment by natebosch** [comment]
I think it is not worth the effort at this point to try to go back and rectify the tags or the published packages.
