### ISSUE TITLE
Is there way to specify headless argument for chrome capability?

### ISSUE THREAD

**Issue by sclee15** [google/webdriver.dart#185]
I hope i can specify the chrome headless argument.

Thank you.

**Comment by eredo** [comment]
You can pass the arguments to the chromedriver in the capabilties. Therefore the capabilities should look like:

```
{"chromeOptions": {"args": ["--headless"] }}
```

See: https://sites.google.com/a/chromium.org/chromedriver/capabilities
And: https://peter.sh/experiments/chromium-command-line-switches/

**Comment by sclee15** [comment]
Thanks
