### ISSUE TITLE
Publish a Dart 2 compatible version?

### ISSUE THREAD

**Issue by leafpetersen** [google/webdriver.dart#205]
It looks like this has been updated with fixes for Dart 2 (e.g. SCREAMING CAPS CONSTANT removal) but not published.  Consider publishing?

**Comment by robbecker-wf** [comment]
any update here?

**Comment by mk13** [comment]
This has been published: https://pub.dartlang.org/packages/webdriver/versions/2.0.0-beta+1

**Comment by chalin** [comment]
The max SDK needs to be updated to 3.0.0. /cc @kevmoo @kwalrath

**Comment by kevmoo** [comment]
@mk13 – can you run on this?
