### ISSUE TITLE
is this package supporting latest webdriver spec?

### ISSUE THREAD

**Issue by sclee15** [google/webdriver.dart#210]
I am trying to use webdriver.dart and i found this error

```
Unhandled exception:
InvalidRequestException (400): Bad Request

#0      processJsonWireResponse (package:webdriver/src/sync/json_wire_spec/response_processor.dart:33:5)
#1      SyncHttpCommandProcessor.post (package:webdriver/src/sync/command_processor.dart:57:12)
#2      createDriver (package:webdriver/sync_core.dart:65:34)
#3      createDriver (package:webdriver/sync_io.dart:32:5)
#4      main (file:///home/sclee/Context/___/___/bin/main.dart:138:22)
```

both w3c spec and json wire shows similar behavior.

Thank you.

**Comment by manuelF** [comment]
What is the webdriver request that is triggering this?

**Comment by zgyorkei** [comment]
I just ran into the same problem:
The ChromeDriverProcess starts succsesfully, after that I'm trying to start the webdriver with the following code:
```
try {
    driver = await createDriver(
        uri: Uri.parse('http://localhost:4444/wd/hub'),
        desired: Capabilities.chrome);
  } catch (Exception) {
    print(Exception.toString());
  }
```
And I get the invalid request error:
```
InvalidRequestException (400): Bad Request
```

**Comment by jingbian** [comment]
W3C is supported. You can try to specify the `spec` parameter like
```
final w3cDriver = createDriver(spec: WebDriverSpec.W3c);
```

If this doesn't work, please file a new bug with more details like Chrome version, webdriver version, test code (request used) etc.
