### ISSUE TITLE
Are there classes to work with html select?

### ISSUE THREAD

**Issue by AlexanderArendar** [google/webdriver.dart#218]
When I was working with Java/Scala language bindings of webdriver there was [Select](https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/support/ui/Select.html) class which I could use to interact with html selects.

Is there something like this in Dart binding?

**Comment by jingbian** [comment]
I don't think we have that.
Also I don't think it's defined in the WebDriver spec.

**Comment by eossa** [comment]
According to the [WebDriver spec](https://www.w3.org/TR/webdriver/#element-click) a workaround for this case is clicking the option, i.e.:

```dart
var option = await driver.findElement(By.cssSelector('select > option[value="foo"]'));
option.click();
```
