### ISSUE TITLE
Add valid copyright information instead of placeholder

### ISSUE THREAD

**Issue by b3arco** [google/webdriver.dart#245]
Currently, in the [LICENSE file](https://github.com/google/webdriver.dart/blob/master/LICENSE), the copyright information is not correct. It literally reads (in line 189):

```diff
Copyright [yyyy] [name of copyright owner]
```

Could you please add a valid year and name?

**Comment by jingbian** [comment]
Fixed in https://github.com/google/webdriver.dart/commit/b51f67a08aee356ae44a4c805d2172f64db660ba
