### ISSUE TITLE
reason for deprecation?

### ISSUE THREAD

**Issue by devoncarew** [google/webdriver.dart#29]
Why was this deprecated in favor of https://github.com/google/dart-sync-webdriver? It seems like `dart-sync-webdriver`'s use of a native lib put pretty heavy restrictions on how it can be used and how easy it is to get it set up.

@DrMarcII (and others)

**Comment by DrMarcII** [comment]
The async api made tests very ugly (at least without await), and I didn't have the resources (or really any compelling reason from my side of things) to maintain both.

However, with support for await there is now one less reason to not use this API, and the difficulties you mention around native extensions make using this version of webdriver more attractive, so I am actually currently revisiting my earlier choice to focus on the dart-sync-webdriver.

**Comment by devoncarew** [comment]
> so I am actually currently revisiting my earlier choice to focus on the dart-sync-webdriver

Makes sense re: making testing simpler, and great that you may be revisiting this. I'm looking using this lib to drive some selenium testing (via saucelabs.com). Setup is definitely easier if we don't have a native ext in the mix.

**Comment by devoncarew** [comment]
Thanks for the info; closing.
