### ISSUE TITLE
issues using this driver with saucelabs and sauce_connect

### ISSUE THREAD

**Issue by devoncarew** [google/webdriver.dart#54]
I'm having trouble getting this driver up and running with saucelabs. I'm using the latest non-dev release, `0.9.1`. What I'm seeing is that the result from the `commandProcessor.post` call in `WebDriver.createDriver()` is a string, not a valid json encoded map:

    "OK,ondemand alive"

Here's the code I'm using:
```dart
import 'dart:io';

import 'package:webdriver/webdriver.dart';

main(List args) async {
  if (args.length < 2) {
    print('usage: sauce <username> <accesskey>');
    exit(1);
  }

  String username = args[0];
  String accessKey = args[1];

  Map caps = Capabilities.firefox;
  caps[Capabilities.version] = "17";
  //capabilities.setCapability("platform", Platform.XP);

  String uri = 'http://${username}:${accessKey}@ondemand.saucelabs.com:80/wd/hub';
  print('Connecting to ${uri}...');

  WebDriver driver = await WebDriver.createDriver(
      uri: Uri.parse(uri),
      desiredCapabilities: caps);
  await driver.get("http://www.amazon.com/");
  print(await driver.title);
  driver.close();
}
```

The code fails when the createDriver call tries to access the `sessionId` from the http post response, when the value is a string and not a  map.

**Comment by devoncarew** [comment]
Happy to try to diagnose things on my end if there's anything I can try -

**Comment by DrMarcII** [comment]
I think you just need to add a '/' to the end of the url.

**Comment by devoncarew** [comment]
Should all urls passed in here end in a slash? Should this method auto-append if it doesn't end in one? Or the docs be updated?

**Comment by DrMarcII** [comment]
Documentation has been updated to indicate that uri should end with trailing slash.

**Comment by zoechi** [comment]
@DrMarcII What documentation does your comment refer to. I couldn't find docs.

**Comment by DrMarcII** [comment]
https://github.com/google/webdriver.dart/blob/master/lib/io.dart#L37
