### ISSUE TITLE
rename `desired` to `capabilities`?

### ISSUE THREAD

**Issue by devoncarew** [google/webdriver.dart#56]
In lib/io.dart:

    Future<WebDriver> createDriver({Uri uri, Map<String, dynamic> desired})

consider renaming the `desired` param to `capabilities`.

**Comment by DrMarcII** [comment]
The WebDriver spec specifies both required and desired capabilities (with required being optional) http://www.w3.org/TR/webdriver/#creating-a-session

I don't include required here because not all remote ends actually support required currently (including, I believe, chromedriver).
