### ISSUE TITLE
WebDriver.get doesn't work

### ISSUE THREAD

**Issue by zoechi** [google/webdriver.dart#57]
```dart
final url = 'http://localhost:${examplePubServePort}/testing/index.html';

// await driver.navigate.to(url); 
await driver.get(url); 

final WebElement someDiv =
          await driver.findElement(const By.cssSelector('* /deep/ #some-div'));
// fails with PhantomJS (with driver.get()): InvalidElementStateException (12): {"errorMessage":"SyntaxError: DOM Exception 12"
// fails with Chrome (with driver.get()): NoSuchElementException (7): no such element
// succeeds with driver.navigate.to() with Chrome and PhantomJS

expect(title, equals('browser/webdriver test'));
expect(someDiv, isNotNull);

await someDiv.attributes['id'] 
// fails with PhantomJs with driver.navigate.to()
// > StaleElementReferenceException (10): {"errorMessage":"Element does not exist in cache"
// succeeds with Chrome with driver.navigate.to()
```
`driver.get` and `WebElement.attributes[]` call `CommandProcessor.get()` while `driver.navigate.to()` calls `CommandProcessor.post()`
I think `driver.findElement()` fails because `driver.get()` doesn't do anything and times out.
In Chrome I see the URL and the page load when `driver.navigate.to()` is used. With `driver.get` the URL is just `data:,` and nothing else happens.

Am I doing something wrong or is this a bug?
`driver.get()` and `driver.navigate.to()` are supposed to do the same thing, aren't they?

> Dart VM version: 1.11.0-edge.45304 (Mon Apr 20 18:15:39 2015) on "linux_x64"

**Comment by zoechi** [comment]
Source: https://github.com/bwu-dart/bwu_utils/blob/master/test/testing/webdriver/polymer/webdriver_test.dart#L49

**Comment by DrMarcII** [comment]
In the version currently checked in, driver.get is not for navigation, it is for sending http GET requests to the selenium server. But the name is confusing, so I am renaming it (and post and delete) in #58

**Comment by zoechi** [comment]
Great,  thanks!
