### ISSUE TITLE
Add some way to scroll an element

### ISSUE THREAD

**Issue by mgreenland** [google/webdriver.dart#67]
Hi,

I'm writing a test where I want to scroll an element (to test some infinite-scroll logic), but it doesn't look like there's any built-in way of doing  that. The Mouse class doesn't seem to expose anything; there's a scroll method in the Touch class, but using that fails with "Underlying driver does not implement advanced user interactions yet.".

I can work around it by modifying the element's scrollTop manually, but it'd be nice to have something that'd trigger all the proper mouse/touch events.

**Comment by DrMarcII** [comment]
The WebDriver spec doesn't include a method for scrolling elements into view.

You can scroll to an element using JavaScript though:
  driver.execute('arguments[0].scrollIntoView();', [element]);
