### ISSUE TITLE
Move API support to package:test

### ISSUE THREAD

**Issue by kevmoo** [google/webdriver.dart#90]
I'm guessing we're blocked on migrating `angular2` to `test`, right?

**Comment by DrMarcII** [comment]
@kevmoo I am not sure what you are asking. This package works fine with test or unittest (the only place that depends on either is the matcher param for waitFor(...) in support/async.dart, and that is currently implemented to work equally well with matchers from package:matcher and package:unittest). Additionally, the tests for webdriver.dart are all actually implemented using package:test.

**Comment by kevmoo** [comment]
Now that I see what you're doing, that makes sense. Once the important users have all moved to pkg/test, removing unittest is a good idea – the `is` checks have a cost.

But that can wait.
