### ISSUE TITLE
How to drag

### ISSUE THREAD

**Issue by zoechi** [google/webdriver.dart#91]
I tried
```dart
      WebElement startResizeHandle =  await driver.findElement(const By.cssSelector('#handle'));
      expect(startResizeHandle, isNotNull);
      await driver.mouse.moveTo(element: startResizeHandle);
      await driver.mouse.down(Mouse.left);
      await driver.mouse.moveTo(xOffset: 50, yOffset: 0);
      await driver.mouse.up(Mouse.left);
```
According to the highlighting the mouse seems to move correctly but no drag'n drop is happening. Should this work this way?

**Comment by DrMarcII** [comment]
This should work, but DnD in WebDriver has always been fiddly. Which browser are you using?

**Comment by zoechi** [comment]
Chrome 44 from selenium/node-chrome-debug:2.46.0, https://github.com/SeleniumHQ/docker-selenium

**Comment by DrMarcII** [comment]
Hmm, Chrome is generally pretty good. Not sure what to suggest. You might have better luck asking people on Selenium mailing lists for help.

**Comment by zoechi** [comment]
Thanks anyway! 
You don't have a test or an example somewhere?

**Comment by zoechi** [comment]
This is a Chrome bug https://code.google.com/p/chromedriver/issues/detail?id=841
Works fine in Firefox

**Comment by zoechi** [comment]
Shouldn't this be sent as collection of actions? It seems WebDriver.dart doesn't support [actions](http://www.w3.org/TR/webdriver/#low-level-actions) yet. Is this planned?

**Comment by DrMarcII** [comment]
AFAIK, none of the remote ends support actions yet (Marionette might I
guess, but I haven't tried it).
