### ISSUE TITLE
Element methods don't operate on the element

### ISSUE THREAD

**Issue by zoechi** [google/webdriver.dart#97]
https://github.com/google/webdriver.dart/blob/master/lib/src/web_element.dart#L36
and similar methods of `WebElement` don't seem to be related to the element they are called on.

`WebElement.click()` is forwarded to `WebDriver._post('click')`. 
I would expect it to move the mouse to the element or select the element before the `click` is invoked.

**Comment by DrMarcII** [comment]
WebElement.click() actually eventually calls WebDriver.post('element/' + id + '/click) which is what it is supposed to do to click on an element (the call to _post at the line in question is a call to WebDriverBase._post).

**Comment by zoechi** [comment]
After a bit of debugging I think I got it. Thanks for your time!
